force-app/main/default/objects/Applicant__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Female</fullName>
                <default>true</default>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/NID__c.field-meta.xml
<CustomField>
    <fullName>NID__c</fullName>
    <label>NID</label>
    <precision>13</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/Asset_Detail__c.object-meta.xml
<CustomObject>
    <label>Asset Detail</label>
    <nameField>
        <label>Field Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Detail__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Asset Details</relationshipLabel>
    <relationshipName>Asset_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Asset_Price__c.field-meta.xml
<CustomField>
    <fullName>Asset_Price__c</fullName>
    <label>Asset Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USED</fullName>
            </value>
            <value>
                <fullName>BRAND NEW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BMW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <label>Serial</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <label>Gurantor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guarantor__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <label>Ownership</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/SSIN_FIEN__c.field-meta.xml
<CustomField>
    <fullName>SSIN_FIEN__c</fullName>
    <label>SSIN</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApplicantCustomControllerTest.cls
@istest
public with sharing class ApplicantCustomControllerTest {
    static String  applicantId;
    static ApplicantCustomController acc = new ApplicantCustomController();
    @istest
    static void TestSaveApplicant(){
       acc.applicant.FirstName__c= 'Wahid';
       acc.applicant.LastName__c= 'Sakib';
       acc.applicant.Email__c= 'RandomString@email.com';
       acc.applicant.Gender__c= 'Male';
       acc.applicant.NID__c= 123456567;
       acc.applicant.Phone__c= '+01854582598';
       acc.applicant.Age__c= 65;
       acc.applicant.Address__c= 'He[pojkdfp[hgiojf[dphij[idpfh';
       acc.applicant.Loan_Amount__c= 1000;

       Pagereference result =  acc.saveApplicant();
       
       Pagereference expected = new Pagereference('/apex/ApplicantForm');
       expected.getParameters().put('id', acc.applicant.id);
       expected.getParameters().put('tab', 'applicant');
       expected.setRedirect(true);

       System.assertEquals(expected.getParameters().get('id'), result.getParameters().get('id'));
       System.assertEquals(expected.getUrl(), result.getUrl());
       System.assertEquals(expected.getRedirect(), result.getRedirect());
       applicantId = acc.applicant.id;
    }

    @istest
    static void TestSaveGuaranor() {
        TestSaveApplicant();
        acc.guarantor.Name__c= 'wSGDSGDSG';
        acc.guarantor.Ownership__c= 100;
        acc.guarantor.SSIN_FIEN__c= 2432445;
        acc.guarantor.Date_of_birth__c= Date.newInstance(2022, 12,6);
        acc.guarantor.Applicant__c = acc.applicant.id;

        Pagereference result =  acc.saveGuarantor();
  
        Pagereference expected = new Pagereference('/apex/ApplicantForm');
        expected.getParameters().put('id', applicantId);
        expected.getParameters().put('tab', 'guarantors');
        expected.setRedirect(true);

        System.assertEquals(expected.getParameters().get('id'), result.getParameters().get('id'));
        System.assertNotEquals(null, result.getParameters().get('guarantorId'));
        // System.assertEquals(expected.getUrl(), result.getUrl());
        System.assertEquals(expected.getRedirect(), result.getRedirect());
    }

    @istest
    static void TestSaveGuaranorAboveHundredOwnership() {
        TestSaveApplicant();
        acc.guarantor.Name__c= 'wSGDSGDSG';
        acc.guarantor.Ownership__c= 102;
        acc.guarantor.SSIN_FIEN__c= 2432445;
        acc.guarantor.Date_of_birth__c= Date.newInstance(2022, 12,6);
        acc.guarantor.Applicant__c = acc.applicant.id;

        Pagereference result =  acc.saveGuarantor();
  
        Pagereference expected = new Pagereference('/apex/ApplicantForm');
        expected.getParameters().put('id', applicantId);
        expected.getParameters().put('tab', 'guarantors');
        expected.setRedirect(false);

        System.assertEquals(expected.getParameters().get('id'), result.getParameters().get('id'));
        System.assertEquals(null, result.getParameters().get('guarantorId'));
        Boolean hasMessage = false;
        for(Apexpages.Message msg: Apexpages.getMessages()){
            if(msg.getDetail().contains('Could not add new Guarantor. Total Ownership exceded 100%')) {
                hasMessage = true;
            }
        }
        System.assertEquals(true, hasMessage);
        System.assertEquals(expected.getRedirect(), result.getRedirect());
    }

    @istest
    static void TestSaveGuaranorAboveHundredOwnershipBySummingUp() {
        TestSaveApplicant();
        TestSaveGuaranor();
        acc.guarantor.Name__c= 'wSGDSGDS34G';
        acc.guarantor.Ownership__c= 60;
        acc.guarantor.SSIN_FIEN__c= 243244532;
        acc.guarantor.Date_of_birth__c= Date.newInstance(2022, 12,6);
        acc.guarantor.Applicant__c = acc.applicant.id;

        Pagereference result =  acc.saveGuarantor();
  
        Pagereference expected = new Pagereference('/apex/ApplicantForm');
        expected.getParameters().put('id', applicantId);
        expected.getParameters().put('tab', 'guarantors');
        expected.setRedirect(false);

        System.assertEquals(expected.getParameters().get('id'), result.getParameters().get('id'));
        System.assertEquals(null, result.getParameters().get('guarantorId'));
        Boolean hasMessage = false;
        for(Apexpages.Message msg: Apexpages.getMessages()){
            if(msg.getDetail().contains('Could not add new Guarantor. Total Ownership exceded 100%')) {
                hasMessage = true;
            }
        }
        System.assertEquals(true, hasMessage);
        System.assertEquals(expected.getRedirect(), result.getRedirect());
    }

    @istest
    static void TestSaveAssetDetails() {
        TestSaveApplicant();
         acc.asset.Asset_Price__c= 1000;
         acc.asset.Condition__c= 'USED';
         acc.asset.Make__c= 'BMW';
         acc.asset.Model__c= 'X9';
         acc.asset.Serial__c= 'SEQDEF';
         acc.asset.Year__c= Date.newInstance(2022, 1, 1);
        Pagereference result =  acc.saveAssetDetail();
  
        Pagereference expected = new Pagereference('/apex/ApplicantForm');
        expected.getParameters().put('id', applicantId);
        expected.getParameters().put('tab', 'asset_details');
        expected.setRedirect(true);

        System.assertEquals(expected.getParameters().get('id'), result.getParameters().get('id'));
        System.assertNotEquals(null, result.getParameters().get('assetDetailId'));
        System.assertEquals(expected.getRedirect(), result.getRedirect());
    }

    @istest
    static void TestSubmit() {
        TestSaveApplicant();
        PageReference result = acc.submit();
        Pagereference expected = new Pagereference('/apex/ApplicantForm');
        expected.getParameters().put('id', applicantId);
        expected.getParameters().put('tab', 'submit');
        expected.setRedirect(true);

        System.assertEquals('Submitted', acc.applicant.Status__c);
        System.assertEquals(expected.getParameters().get('id'), result.getParameters().get('id'));
        System.assertEquals(expected.getUrl(), result.getUrl());
        System.assertEquals(expected.getRedirect(), result.getRedirect());
    }

    @istest
    static void TestGetApplicant() {
        TestSaveApplicant();
        Applicant__c result = acc.getApplicant(acc.applicant.id);
        System.assertEquals(result.id, acc.applicant.id);

    }

    @istest
    static void TestGetGuarantors() {
        TestSaveApplicant();
        TestSaveGuaranor();
        List<Guarantor__c> result = acc.getGuarantors(acc.applicant.id);
        System.assertNotEquals(0, result.size());

    }

    @istest
    static void TestGetAssetDetails() {
        TestSaveApplicant();
        TestSaveAssetDetails();
        List<Asset_Detail__c> result = acc.getAssetDetails(acc.applicant.id);
        System.assertNotEquals(0, result.size());

    }
}