force-app/main/default/objects/Applicant__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Female</fullName>
                <default>true</default>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/NID__c.field-meta.xml
<CustomField>
    <fullName>NID__c</fullName>
    <label>NID</label>
    <precision>13</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/Asset_Detail__c.object-meta.xml
<CustomObject>
    <label>Asset Detail</label>
    <nameField>
        <label>Field Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Detail__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Asset Details</relationshipLabel>
    <relationshipName>Asset_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Asset_Price__c.field-meta.xml
<CustomField>
    <fullName>Asset_Price__c</fullName>
    <label>Asset Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USED</fullName>
            </value>
            <value>
                <fullName>BRAND NEW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BMW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset_Detail__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <label>Serial</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVOICE</fullName>
            </value>
            <value>
                <fullName>BANK STATEMENT</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <label>Gurantor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guarantor__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Guarantors</relationshipLabel>
    <relationshipName>Guarantors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <label>Ownership</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/SSIN_FIEN__c.field-meta.xml
<CustomField>
    <fullName>SSIN_FIEN__c</fullName>
    <label>SSIN</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApplicantCustomController.cls
public with sharing class ApplicantCustomController {
    public Applicant__c applicant{get;set;}
    public Guarantor__c guarantor{get; set;}
    public Document__c document{get; set;}
    public Asset_Detail__c asset{get; set;}
    public List<Guarantor__c> guarantors{get;set;}
    public List<Document__c> documents{get;set;}
    public List<Asset_Detail__c> assets{get;set;}
    public blob file{get;set;}
    public String fileName{get; set; }
    
    public ApplicantCustomController(){
        this.applicant = new Applicant__c();
        this.guarantor = new Guarantor__c();
        this.document = new Document__c();
        this.asset = new Asset_Detail__c();
        
        String applicantId = ApexPages.currentPage().getParameters().get('id');
        
        if(applicantId != null){
            this.getApplicant(applicantId);
            this.getGuarantors(applicantId);
            this.getAssetDetails(applicantId);
            this.getDocuments(applicantId);
        }
    }
    
    public Applicant__c getApplicant(String id){
        this.applicant = [SELECT FirstName__c, 
                          LastName__c, 
                          Address__c, 
                          Email__c,
                          Gender__c,
                          NID__c,
                          Phone__c,
                          Loan_Amount__c,
                          Status__c,
                          Age__c FROM Applicant__c WHERE id = :id];
        return this.applicant;
    }
    
    public List<Guarantor__c> getGuarantors(String applicantId){
        this.guarantors = [SELECT Name__c, 
                          Ownership__c, 
                          SSIN_FIEN__c, 
                          Date_of_birth__c
                          FROM Guarantor__c WHERE applicant__c = :applicantId];
        return this.guarantors;
    }
    
    public List<Asset_Detail__c> getAssetDetails(String applicantId){
        this.assets = [SELECT Asset_Price__c, 
                          Condition__c, 
                          Make__c, 
                          Model__c,
                          Serial__c,
                          Year__c
                          FROM Asset_Detail__c WHERE applicant__c = :applicantId];
        return this.assets;
    }

    private void getDocuments(String applicantId){
       this.documents= [SELECT Type__c, 
                          Name__c, 
                          File_Name__c 
                          FROM Document__c WHERE applicant__c = :applicantId];
    }

    public PageReference saveApplicant(){
        UPSERT this.applicant;
        Pagereference pr = new Pagereference('/apex/ApplicantForm');
        pr.getParameters().put('id', this.applicant.id);
        pr.getParameters().put('tab', 'applicant');
        pr.setRedirect(true);
        return pr;
    }
    
    public PageReference saveGuarantor(){
        try{
            Decimal totalOwnership = this.guarantor.Ownership__c;
            for (Guarantor__c g : this.guarantors == null ? new List<Guarantor__c>() : this.guarantors) {
                totalOwnership += g.Ownership__c;
            }

        if(totalOwnership > 100){
             NoAccessException na = new NoAccessException();
             na.setMessage('Could not add new Guarantor. Total Ownership exceded 100%');
             throw na;
        }
        this.guarantor.Applicant__c = this.applicant.id;
        UPSERT this.guarantor;
        this.getGuarantors(this.applicant.id);
        Pagereference pr = new Pagereference('/apex/ApplicantForm');
        pr.getParameters().put('id', this.applicant.id);
        pr.getParameters().put('tab', 'guarantors');
        pr.getParameters().put('guarantorId', this.guarantor.id);
        pr.setRedirect(true);
        this.guarantor = new Guarantor__c();
        return pr;
        }
        catch(Exception e){
            ApexPages.Message message = new Apexpages.Message(Apexpages.Severity.Error, e.getMessage());
            Apexpages.addMessage(message);
            Pagereference pr = new Pagereference('/apex/ApplicantForm');
            pr.getParameters().put('id', this.applicant.id);
            pr.getParameters().put('tab', 'guarantors');
            pr.setRedirect(false);
            return pr;
        }
        
    }
    public PageReference saveAssetDetail(){
        this.asset.Applicant__c = this.applicant.id;
        upsert this.asset;
        Pagereference pr = new Pagereference('/apex/ApplicantForm');
        pr.getParameters().put('id', this.applicant.id);
        pr.getParameters().put('tab', 'asset_details');
        pr.getParameters().put('assetDetailId', this.asset.id);
        pr.setRedirect(true);
        this.asset = new Asset_Detail__c();
        this.getAssetDetails(this.applicant.id);
        return pr;
    }
    public PageReference saveDocument(){
        try{
            ContentVersion v = new ContentVersion();
            v.versionData = file;
            v.title = this.fileName;
            v.ContentLocation = 's';
            v.PathOnClient='/';
            insert v;

            this.document.Applicant__c = this.applicant.id;
            UPSERT this.document;
            this.document = new Document__c();
            this.getDocuments(this.applicant.id);
            return null;
        }catch(Exception e){
            ApexPages.Message message = new Apexpages.Message(Apexpages.Severity.Error, e.getMessage());
            Apexpages.addMessage(message);
            return null;
        }
        
    }
    public PageReference submit(){
        this.applicant.Status__c = 'Submitted';
        UPSERT this.applicant;
        Pagereference pr = new Pagereference('/apex/ApplicantForm');
        pr.getParameters().put('id', this.applicant.id);
        pr.getParameters().put('tab', 'submit');
        pr.setRedirect(true);
        return pr;
    }
    
    
}